import bst
b=bst.BST()
b.insert("i")
b.insert("j")
b.insert("l")
b.insert("free",25)
b.insert("b")
b.insert("google")
b.insert("cat")
b.insert("ant")
b.insert("nag")
b.insert("ipsum")
b.insert("kick")
b.insert("fbi")
b.insert("hat",[10,20])
b.insert("jack")
b.insert("illussion")
print repr(b)
b,remove("i")
print repr(b)
b,remove("ipsum")
print repr(b)
b.remove("google")
print repr(b)
b.remove("illussion")
print repr(b)